### ISSUE TITLE
Add other depot packages to the download cache

### ISSUE THREAD

**Issue by martenson** [erasche/community-package-cache#14]
e.g. should the urls from https://depot.galaxyproject.org/software/ be available in the file thus making it the universal resource for package location?

**Comment by erasche** [comment]
yes, definitely. Will add support for those.

**Comment by erasche** [comment]
FINALLY Done. Other depot packages are symlinked in since redirects weren't an option.

**Comment by erasche** [comment]
https://jenkins.galaxyproject.org/view/Meta/job/community-package-cache/
