### ISSUE TITLE
should we declare the level of trust of an url?

### ISSUE THREAD

**Issue by martenson** [erasche/community-package-cache#15]
e.g. should https://depot.galaxyproject.org/software/ be more trustworthy download source than e.g. sourceforge (and thus have redirect priority)?

**Comment by erasche** [comment]
I think this adds unnecessary complexity.

- for all non-Galaxy URLs we designate as "untrusted" and just download the file.
- for all Galaxy sponsored URLs we're assuming the devteam can do a bit better than everyone else, hence my comment in #14 that it should be OK to redirect to devteam URLs but require downloads for others.

The redirection capability was put in at @natefoo's request in the original RFC in the IUC repo for this exact case I believe

**Comment by martenson** [comment]
Sounds great.
