### ISSUE TITLE
Rename packages for transparency in URL use.

### ISSUE THREAD

**Issue by martenson** [erasche/community-package-cache#16]
at https://depot.galaxyproject.org/software/ if you download some package e.g. https://depot.galaxyproject.org/software/30e84ac4b31d40b66293f7b1221331c5a50561a39d580d85004d9c1fff991751

you will get a file named 30e84ac4b31d40b66293f7b1221331c5a50561a39d580d85004d9c1fff991751 that does not have any extension

This is quite confusing.

**Comment by erasche** [comment]
ahh yes. I haven't come up with any solutions to this yet, so I'll be happy to hear opinions.

- should we construct a whole filename, based on package name + version + architecture + archive type (new column)?
- should we just annotate archive type?

Let me know your thoughts on this :)
