### ISSUE TITLE
Track package download statistics

### ISSUE THREAD

**Issue by erasche** [erasche/community-package-cache#20]
with a little help from our friend @natefoo?

Can we? Pretty please? :) Should be as simple as just grepping the logs for `/software` and and aggregating those somewhere accessible.

**Comment by erasche** [comment]
Also who does analytics for the project? Should we have a tracking snippet in that page?

**Comment by natefoo** [comment]
Sure, got a script? =)

For analytics, ping @martenson

**Comment by martenson** [comment]
include
```
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45719423-15', 'auto');
  ga('send', 'pageview');

</script>
```

**Comment by erasche** [comment]
@natefoo sure, got example logs so I can write appropriate grep/awk/sed?
@martenson thanks! :)

**Comment by natefoo** [comment]
@erasche sorry for the delay, you should be able to read the logs under /var/log/nginx as your regular user on orval.

**Comment by erasche** [comment]
@natefoo yeah, I realised that a week ago and then have been slowly getting around to actually scripting the process. Sorry for the unnecessary ping.
