### ISSUE TITLE
recommendation for unique package identifier

### ISSUE THREAD

**Issue by bgruening** [erasche/community-package-cache#3]
We need a recommendation for a package naming schema.
`name` _ `major-version` _ `minor-version`?

**Comment by erasche** [comment]
maybe we should separate version into a (new) 2nd column which just has the complete version string. Not distinguish between major/minor since goodness knows upstream won't.

**Comment by erasche** [comment]
(Working on separating out version numbers into col2 now)

**Comment by erasche** [comment]
Removed earlier comments as I've separated out version numbers into a new column. I'm fine with `{major}_{minor}` naming scheme.

**Comment by erasche** [comment]
@bgruening how do you feel about these:

- `stringtie_1_0_4_darwin-x64`, `sendmailR_1.2-1_src-all`
- `stringtie-1_0_4-darwin-x64`, `sendmailR-1.2-1-src-all`

**Comment by erasche** [comment]
Since we have the option, I'd like to rewrite ALL versions to normal version identifiers (with dots/dashes, as are used by upstream), and then join on underscores. The above examples will become

`stringtie_1.0.4_darwin_x64.tar.gz` and `sendmailR_1.2-1_src_all.tar.gz`

**Comment by bgruening** [comment]
:+1:
